name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Run code linter
        run: pnpm run lint

      - name: Run type checker
        run: pnpm run type-check

      - name: Run formatting check
        run: pnpm run format-check
